name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: ./OrganizationSolution/Source

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./OrganizationSolution/Source
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Restore dependencies
      run: dotnet restore AWSServerless3.csproj
    - name: Build
      run: dotnet build --no-restore AWSServerless3.csproj
    - name: Deploy to Lambda
      working-directory: ./OrganizationSolution/Source
      run: dotnet lambda deploy-serverless