name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: ./OrganizationSolution/Source/App/Geography.Serverless

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./OrganizationSolution/Source/App/Geography.Serverless
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_USERPOOL_CLIENT_ID: ${{secrets.AWS_USERPOOLCLIENTID_KEY }}
      AWS_USERPOOL_ID: ${{secrets.AWS_USERPOOLID_KEY }}
      AWS_USERPOOL_CLIENT_SECRET: ${{secrets.AWS_USERPOOLCLIENTSECRET_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Restore dependencies
      run: dotnet restore Geography.Serverless.csproj
    - name: Build
      run: dotnet build --no-restore Geography.Serverless.csproj
    - name: test cases
      working-directory: ./OrganizationSolution/Source/Test/Geography.ServerlessTests
      run: |
          ls
          --environment ASPNETCORE_ENVIRONMENT="Production" --environment AWSConfigurationOptions__ClientId="AKIA25YN4OYKSKWOIHV5" --environment AWSConfigurationOptions__ClientSecret="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" --environment AWSConfigurationOptions__UserPoolClientId="68ohnv3bhi64k08riiqfu1b1pk" --environment AWSConfigurationOptions__UserPoolId="us-west-2_JojgZLDdW" --environment AWSConfigurationOptions__UserPoolClientSecret= ${{secrets.AWS_USERPOOLCLIENTSECRET_KEY }}
          dotnet test Geography.ServerlessTests.csproj 
    - name: Deploy to Lambda
      working-directory: ./OrganizationSolution/Source/App/Geography.Serverless
      run: dotnet lambda deploy-serverless
