name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: ./OrganizationSolution/Source/App/Geography.Serverless

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./OrganizationSolution/Source/App/Geography.Serverless
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_USERPOOL_CLIENT_ID: ${{secrets.AWS_USERPOOLCLIENTID_KEY }}
      AWS_USERPOOL_ID: ${{secrets.AWS_USERPOOLID_KEY }}
      AWS_USERPOOL_CLIENT_SECRET: ${{secrets.AWS_USERPOOLCLIENTSECRET_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Restore dependencies
      run: dotnet restore Geography.Serverless.csproj
    - name: Build
      run: dotnet build --no-restore Geography.Serverless.csproj
    - name: test cases
      working-directory: ./OrganizationSolution/Source/Test/Geography.ServerlessTests
      run: |
          ls
          dotnet test --no-restore --verbosity normal --Geography.ServerlessTests.csproj --env AWSConfigurationOptions__ClientId = ${{ secrets.AWS_ACCESS_KEY_ID }} --env AWSConfigurationOptions__ClientSecret= ${{ secrets.AWS_SECRET_ACCESS_KEY }} --env AWSConfigurationOptions__UserPoolClientId= ${{secrets.AWS_USERPOOLCLIENTID_KEY }} --env AWSConfigurationOptions__UserPoolClientSecret= ${{secrets.AWS_USERPOOLCLIENTSECRET_KEY }} --env AWSConfigurationOptions__UserPoolId= ${{secrets.AWS_USERPOOLID_KEY }} 
    - name: Deploy to Lambda
      working-directory: ./OrganizationSolution/Source/App/Geography.Serverless
      run: dotnet lambda deploy-serverless
